theme: jekyll-theme-minimal
title: Welcome to HuiChee's homepage!
description: Feel free to visit this page~
heading: HUI CHEE
introducing paragraph: I'm Hui Chee. I'm a malaysian, and now studying in National Tsing Hua University. My major is computer science, I haven't learn about any type of c language before I come to study, and I feel that it is really difficult to me...
ordered list: Study in National Tsing Hua University, Hsinchu, Taiwan
ordered list: Malaysian
ordered list: edeline2001@gamil.com
unordered list: ABOUT
unordered list: EDUCATION
